#!/bin/bash
#
# GLXC EXPORT: SYSCONF -> GIT files
#

. /usr/share/glxc/export.init.bash || exit 2

[ -z "$GLXC_DATA_PATH" ] && nef_fatal "missing variable: GLXC_DATA_PATH"

state_ref=$(glxc_state_ref_name sysconf)

if [ -d /sysconf/.git ]; then

    (
        local_git_dir=$GIT_DIR # local_git_dir is the path to "/local.repository.git"
        unset GIT_DIR
        unset GIT_WORK_TREE
        unset GIT_INDEX

        cd /sysconf

        # "$state_ref" in the /sysconf dir points to the commit that was
        # last merged into $local_git_dir
        if [ "$(git show-ref -s $state_ref)" != "$(git show-ref -s refs/heads/master)" ]; then

            nef_log "/sysconf head master has changed. Integrating back the changes..."

            # Clone a non-bare repository our of the central local one, to please git-subtree
            temp_branch=$(date +T%s)
            clone_path=/tmp/$temp_branch
            # git clone $local_git_dir $clone_path 2>&1 | nef_log_pipe "git-clone:" || nef_fatal "git clone failed"
            nef_log "Copying $local_git_dir to: $clone_path/.git"

            nef_cmd -- mkdir $clone_path
            nef_cmd -- cp -a $local_git_dir $clone_path/.git
            cd $clone_path
            nef_cmd --log-prefix git-config -- git config --bool core.bare false
            nef_cmd --log-prefix git-symbolic-ref -- git symbolic-ref HEAD refs/heads/master
            nef_cmd --log-prefix git-readtree -- git read-tree HEAD
            nef_cmd --print -- pwd

            nef_cmd --log-prefix git-checkout-index -- git checkout-index -u -a
            nef_cmd --print -- ls -l $clone_path


# mkdir $clone_path || nef_fatal "mkdir has failed"
# cp -a $local_git_dir $clone_path/.git 2>&1 | nef_log_pipe "cp:" || nef_fatal "cp(1) has failed"
# cd $clone_path
# git config --bool core.bare false || nef_fatal
# git read-tree HEAD 2>&1 | nef_log_pipe "git-read-tree:" || nef_fatal "git-readtree(1) has failed"
# [ ${PIPESTATUS[0]} -ne 0 ] && nef_fatal "git-readtree(1) failed with status ${PIPESTATUS[0]}"
# git checkout-index -u -a 2>&1 | nef_log_pipe "git-checkout-index:"
# [ ${PIPESTATUS[0]} -ne 0 ] && nef_fatal "git-checkout-index(1) failed with status ${PIPESTATUS[0]}"
            nef_log "Done cloning."

            nef_log "Executing: git subtree pull -P '$GLXC_DATA_PATH' /sysconf master"
            nef_cmd --log-prefix git-subtree -- git subtree pull -P $GLXC_DATA_PATH /sysconf master \
                -m "Automatic merge (git-subtree pull) by $0 on $(hostname)"

            # git subtree pull -P $GLXC_DATA_PATH /sysconf master \
            #     -m "Automatic merge (git-subtree pull) by $0 on $(hostname)" 2>&1 | nef_log_pipe "git-subtree:"
            # _status=${PIPESTATUS[0]}
            # [ $_status -ne 0 ] && nef_fatal "git-subtree(1) failed with status $_status"

            nef_cmd --log-prefix git-push -- git push $local_git_dir master
            # git push origin master 2>&1 | nef_log_pipe "git-push:" || nef_fatal "git push failed"

            cd /sysconf
            rm -rf $clone_path

            message="update after exporting sysconf (as a subtree) to the local repository"
            git update-ref -m "$message" $state_ref refs/heads/master

            cd $local_git_dir
            message="update after sysconf subtree merge"
            git update-ref -m "$message" $state_ref refs/heads/$GLXC_GIT_BRANCH $glxc_last_commit

        else
            nef_log "No change committed in /sysconf in branch master"
        fi

    ) || nef_fatal "sub-command failed"

else
    nef_log "/sysconf/.git does not exist, ignored."
fi
